name: 'Maths'
description: 'The maths library using MPFR for high precision'
output: 'lib/maths_generated_bindings.dart'
llvm-path:
  - '/nix/store/kzdjmvi972r95fxv96h90ns38mpq4gj2-clang-16.0.6-lib'
headers: 
  entry-points:
    - 'maths/src/Expose.h'
compiler-opts:
  - '-idirafter /nix/store/41pf3md9zgpda9kwh6rzn5kaddf7i0lp-glibc-2.40-66-dev/include '
  - '-isystem /nix/store/6i862vz60awrlsila8vw18rg4d4l66iy-gcc-14.2.1.20250322/include/c++/14.2.1.20250322 -isystem /nix/store/6i862vz60awrlsila8vw18rg4d4l66iy-gcc-14.2.1.20250322/include/c++/14.2.1.20250322/x86_64-unknown-linux-gnu '
  - '-isystem /nix/store/a7hv40d3zraccd4axsghjsb8svblh97f-clang-wrapper-16.0.6/resource-root/include'
  - '-isystem /nix/store/0r0mg0wd6g5ghhi93wn0kyzbdnl5xgka-gmp-with-cxx-6.3.0-dev/include'
  - '-isystem /nix/store/jwsr7dfrz99j71rczbi5nxygdwb0z1v6-mpfr-4.2.2-dev/include'
